Repository wecode-bootcamp-korea/43-backend-westagram-1, pull requests merged in 2023-02, with the labels that each got.

#1 [ADD] express 초기셋팅
  kyunghun/.gitignore
  kyunghun/app.js
  kyunghun/package-lock.json
  kyunghun/package.json
Labels: 완료

#3 [강종범] Assignment 1: Express API - 초기 환경 세팅
  jongbeom/app.js
  jongbeom/package-lock.json
  jongbeom/package.json
Labels: 멘토 리뷰 요청

#2 [장지원] Assignment 1: Express API - 초기 환경 세팅
  jiwonjang/.env.sample
  jiwonjang/.gitignore
  jiwonjang/app.js
  jiwonjang/package-lock.json
  jiwonjang/package.json
Labels: 멘토 리뷰 요청

#6 [장지원] Assignment 2: Express API - 유저 회원가입 하기
  jiwonjang/.env.sample
  jiwonjang/.gitignore
  jiwonjang/app.js
  jiwonjang/db/migrations/20230222082324_create_user_table.sql
  jiwonjang/package-lock.json
Labels: 멘토 리뷰 요청

#4 [류승준] Assignment 1: Express API - 초기 환경 세팅
  seungjun/.env.sample
  seungjun/.gitignore
  seungjun/app.js
  seungjun/package-lock.json
  seungjun/package.json
Labels: 멘토 리뷰 요청

#11 [김수현]Assignment2: Express API - 유저 회원가입 하기
  kimsoohyun/app.js
Labels: 멘토 리뷰 요청

#14 [류승준] assignment2 - 유저 회원가입
  seungjun/.gitignore
  seungjun/app.js
  seungjun/db/migrations/20230227014652_create_users.sql
Labels: 수정 요청

#10 [장지원] Assignment 3: Express API - CRUD
  jiwonjang/.env.sample
  jiwonjang/.gitignore
  jiwonjang/app.js
  jiwonjang/db/migrations/20230222082324_create_user_table.sql
  jiwonjang/db/migrations/20230223061228_create_post_table.sql
  jiwonjang/db/migrations/20230224070337_likes.sql
Labels: 멘토 리뷰 요청

#13 [김승태]Assignment 2 - 유저 회원가입 하기
  seungtae/.gitignore
  seungtae/app.js
  seungtae/db/migrations/20230226102607_create_users_table.sql
  seungtae/db/migrations/20230226102609_create_posts_table.sql
  seungtae/db/migrations/20230226102612_create_comments_table.sql
  seungtae/db/migrations/20230226102614_create_likes_table.sql
Labels: 멘토 리뷰 요청
